### ISSUE TITLE
Issue with the Alpha AppImage

### ISSUE THREAD

**Issue by probonopd** [saleae/gitbook-docs#1]
Thank you very much for providing Logic in AppImage format for Linux. As the author of AppImageKit I'd like to work with you to turn it into the best experience possible.

https://github.com/saleae/gitbook-docs/blob/2c78f8991a792e0ed33de8fc8d69e53ad08a550b/logic-software/alpha-release.md#saleae-logic-1230-alpha

Please see https://github.com/AppImage/appimage.github.io/pull/803 for issues with this AppImage. Thanks.

**Comment by Marcus10110** [comment]
Thanks! I want to leave this issue open until we fix it. I'll work on getting this fixed in one of the upcoming releases. The next alpha release is running pretty behind now, so I'll bump this and try to get to it in the following release.

**Comment by timreyes** [comment]
Hi. We have committed to getting this fixed before the production release of our alpha software. I'll be closing this issue now since we've got these details committed and logged on our roadmap. Feel free to check in on our progress of the alpha release below:
https://support.saleae.com/logic-software/alpha-release
