### ISSUE TITLE
Display all analog channels with same voltage scale

### ISSUE THREAD

**Issue by jporter4** [saleae/gitbook-docs#12]
Hi,  the attachment will illustrate what I am talking about here.  I'm using a LogicPro16 and software version 1.2.18.  I used one digital channel and 9 analog channels to capture the state of some of the pins on an Espressif ESP-Launcher board at startup.  The rising edge of digital channel 09 (VDD33) is the trigger.  The display seems to indicate that both channels 11 and 12 rise to a logic high about 1 msec after the trigger - but if you look closer, they're displayed with different voltage scales, and channel 12 actually only rises to about 0.8V.  It's very misleading.  Likewise, at first glance it appears that channel 15 is near 0V the entire trace (except for the spike at powerup) - until you see that the scale for channel 15 is only 3V-4V, and it's actually at 3.3V the entire trace.  Again, very misleading.  It's fantastic that the Pro16 has these analog capabilities, it almost replaces having to hook up a scope for signals that are in no-man's land (like channels 12 and 14).  But an actual oscilloscope wouldn't force you to use a misleading set of voltage scales on the different channels.  BTW I've got all the channels set for 2x.  
[ESP-Launcher_startup.pdf](https://github.com/saleae/gitbook-docs/files/3355249/ESP-Launcher_startup.pdf)
Thank you, John Porter

**Comment by timreyes** [comment]
Hi John, thanks for the feedback, and I'm really sorry for the trouble with that. We hear you! We're working on getting this fixed in the new version of our Logic software (now in Alpha).
https://discuss.saleae.com/

We will be adding in adjustable voltage scaling.

If you want to discuss further, feel free to email me at support@saleae.com, or drop your comments in the link here: https://discuss.saleae.com/

Thanks again for writing this up. We weren't too happy with how we automatically handled voltage scaling in the past, so we will get this fixed soon.
