### ISSUE TITLE
Absolute timestamp

### ISSUE THREAD

**Issue by saloid** [saleae/gitbook-docs#19]
Is there any way to switch timeline or export csv file with absolute time (set in system)? I need it to correlate logged events with received packets via UART or something else.

**Comment by timreyes** [comment]
Unfortunately there is no way to do this at the moment. There are a few users that have noted their need for this as shown in the idea link below:
https://ideas.saleae.com/b/feature-requests/timing/

Feel free to vote/comment on it and include your use case! It would be nice to have a record of it so that we can review it in future discussions of our roadmap. Sorry again this isn't available yet.
