### ISSUE TITLE
App won't start on Surface Book 3

### ISSUE THREAD

**Issue by matsujirushi** [saleae/gitbook-docs#22]
Hi,
I changed PC. Surface Pro 4 to Surface Book 3.
Saleae Logic 1.2.18 won't start on Surface Book3.

Error log is attached.
Please help!!
[08_14_2020__17_02_04.txt](https://github.com/saleae/gitbook-docs/files/5073344/08_14_2020__17_02_04.txt)

**Comment by timreyes** [comment]
I'm so sorry to hear this! This looks like a compatibility issue with your Surface Pro/Book.

Can you send me (Tim) a message using the link below?
https://contact.saleae.com/hc/en-us/requests/new

In your message, please include your shipping information since we might need to send a replacement.
 - Full name
 - Address
 - Phone number
 - Which Saleae Logic device you own, and what color? Please refer to the link below:
https://support.saleae.com/faq/general-faq/identify-each-saleae-device
