### ISSUE TITLE
Analog vs Digital capture differences

### ISSUE THREAD

**Issue by mikestrauser** [saleae/gitbook-docs#26]
I am connected to an RS-485 pair.  I want to capture using digital so I can use the protocol analyzer to see the bytes.  There is a glitch which does not appear in the analog capture - or on my Tek scope.  It doesn't do this everytime, but most of the time.
![Capture](https://user-images.githubusercontent.com/46457035/101220683-f2890080-363a-11eb-9816-5f67d5c49713.PNG)
![Capture2](https://user-images.githubusercontent.com/46457035/101220685-f3219700-363a-11eb-876a-0c7bc26bff10.PNG)

**Comment by timreyes** [comment]
Sorry to hear about this! I suspect your signal is hovering around the voltage threshold of our Logic 8, which is causing the glitches. More information below for the voltage threshold value:
https://support.saleae.com/user-guide/supported-voltages

I might suggest using our software glitch filter to help with this:
https://support.saleae.com/user-guide/using-logic/software-glitch-filter

I'll close this GitHub issue now since we reserve Issues here for documentation issues specifically. In case you'd like me to help any further, please send me a message below and let me know that we talked on github and I'll know it's you:
https://contact.saleae.com/hc/en-us/requests/new
