### ISSUE TITLE
How to Trigger On a Pulse with No Maximum Time Limit in Logic 2

### ISSUE THREAD

**Issue by mhkline** [saleae/gitbook-docs#32]
I don't see the option for "n/a" as maximum limit in Logic 2. Is it possible to set up a trigger this way?

https://github.com/saleae/gitbook-docs/blob/master/faq/technical-faq/how-to-trigger-on-a-pulse-with-no-maximum-time-limit.md

**Comment by timreyes** [comment]
Apologies this isn't available yet. We're currently tracking this idea in the link below:
https://ideas.saleae.com/b/feature-requests/trigg-on-signal-state-low-high-after-x-time/

Feel free to add your vote/comment(s) to it. In the meantime, I added a comment for you.

I'll close this Issue now, since we track feature requests using the idea site above. Thanks for letting us know your need for this!
