### ISSUE TITLE
Analyzers tab Data Table bug

### ISSUE THREAD

**Issue by lukabosnjakovic** [saleae/gitbook-docs#38]
Hello,

I'm using Logic 2 software
`{"Environment":"production","Branch":"master","Commit":"fffb7548bedaec4fbc81f9b2acb8b1635dfda2a4","Version":"2.3.33","MachineID":"654894d1-1132-4c34-885b-b49ef0099180","PID":15420}`
with Logic 8 device (but device isn't problem I suppose).

The problem is with Analyzers tab. In that tab you have feature that you show decoded data in a table. But problem is that some rows in that table are missing. Here is a screenshoot:
![image](https://user-images.githubusercontent.com/5735720/129851232-1f6c38b1-be98-4a23-8952-6f37e1ae36a2.png)
As you can see in yellow line row is missing with data 0x80. And the best thing when you switch from table to terminal missing data is there:
![image](https://user-images.githubusercontent.com/5735720/129851507-8640b7c6-388c-448a-87fe-5720dfef2562.png)

I suppose there is bug when parsing data into table. This problem is constant because when I got longer record (more data) I find out that there are more than one row missing

**Comment by timreyes** [comment]
@lukabosnjakovic Thanks for reporting this to us, and providing all of this information.

I'd like to get a support ticket open for this and have our software team take a look This is actually the first we've heard of this bug.

Would you mind doing the following?
1. Open up a support ticket using the link below:
- https://contact.saleae.com/hc/en-us/requests/new

2. Attach a copy of your capture file in the link above. Instructions on exporting the .sal capture file are below:
- https://support.saleae.com/user-guide/using-logic/saving-loading-and-exporting-data

3. In the "Description" box for the support ticket from step (1), provide a link to this GitHub issue so that I know it's you that's writing it in.

In the meantime, I'll go ahead and close the GitHub issue here, since these are primarily used to indicate typos or issues related to our support documentation.

Looking forward to chatting further via email and getting this solved!
