### ISSUE TITLE
Silent install

### ISSUE THREAD

**Issue by Agivx3** [saleae/gitbook-docs#5]
How can the software be silenty installed ?

I tried extracting it and used the msi and mst but they keep failing. 
Are there additional params needed ?

**Comment by Agivx3** [comment]
Anything new about this ?

**Comment by timreyes** [comment]
We ran some more tests, and it looks like it doesn't quite work as we expected. We also tried extracting out the .msi and .mst files but we could not find success with those. Sorry about that...

One workaround I can think of would be to extract the standalone installer to the folder of your choice. Standalone can be found below.
https://support.saleae.com/logic-software/latest-beta-release

Unfortunately, this still means you need to install the Saleae drivers manually since the standalone doesn't do this automatically. Sorry we don't have a clean short term solution for this...
